# stage 1: install dependencies
FROM node:22-alpine3.19 AS dependencies

WORKDIR /app

COPY client/package*.json ./
COPY client/yarn.lock ./

RUN yarn install

# stage 2: build the client app
FROM dependencies AS build

WORKDIR /app

COPY client ./

RUN yarn build

# stage 3: use Nginx as the production server
FROM nginx:alpine

# copy the built React app to Nginx's web server directory
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

# expose port 80 for the Nginx server
EXPOSE 80

# start Nginx
CMD ["nginx", "-g", "daemon off;"]
